### ISSUE TITLE
Can't authorize device?

### ISSUE THREAD

**Issue by FezVrasta** [eslavnov/android-tv-remote#1]
Hi, I have a 65OLED873/12 and I can't seem to get adb to get authorized, the auth popup doesn't show up on my TV.

is there any particular step to follow?

I enabled adb debugging and:

```
adb connect IP
adb shell
```

**Comment by eslavnov** [comment]
Hey Federico,

This is strange, let's test a couple of things to understand what's going on:

1) What's the output when running `adb connect %tv_ip%`? (please run this in your terminal/command line)
2) Next please run `adb devices` - what's the output? (again - in your terminal, not in the tool)
3) Finally, please go into developer settings on your TV and look for any disabled settings with "debugging" in them, try enabling them and then try `adb connect %tv_ip%` again - different devices have a slightly different set of settings to allow LAN/WI-FI debugging (I've seen "USB debugging", "TCP/IP debugging", "Wi-Fi debugging" and others on my devices...), so it could be some extra setting that you need to enable.

**Comment by FezVrasta** [comment]
Thanks for the reply!

I actually managed to make the popup show up by connecting to the TV as soon I turned it on after a while it was off.

I'm not sure why that way it worked 🤷‍♂️

**Comment by jariz** [comment]
For anyone finding this through google: the problem seems to be that the popup does not get shown when you're on the homescreen, so switch to a source (a channel our input) instead.

**Comment by lesnitsky** [comment]
@jariz you saved my day

**Comment by popy2k14** [comment]
Hey guys.

Also facing this issue with my 65PUS8102 on oreo:

```
python3 android-tv-remote.py --host 192.168.0.4 --input 1
Connected to 192.168.0.4
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
Error connecting to TV
```
The popup just dont appear.
Have tried the following:

- adb kill-server
- restarted all devices
- delete all authorizations
- manually create an new authorization on the client with adb keygen
- copy the public key to the tv -> not possible because philips has secured the system down. cant access /data/misc/adb directory without an permission error
- installed Termux and run input keyevent KEYCODE_F1 (or other) -> permission error
- installed telnet from playtore, connect to the tv and run the above -> same error
- tried @jariz idea from above and switched to HDMI1 ... sadly no auth popup...

Any ideas?

thx

**Comment by FezVrasta** [comment]
Try to go to a TV channel, I read the popup doesn't show up on the Android TV home screen for some users

**Comment by popy2k14** [comment]
Already tried to switch to an input (HDMI), but no popup.
Sadly, i have no channels installed because i am watching TV over kodi and addons.

Any other ideas?

**Comment by popy2k14** [comment]
Finally i was able to get adb working/authorized by:

- installing tv channels (had to connect cable from my backend server to the tv)
- switching to any FTA channel
- rebooted the tv
- authorization dialog poped up

So the information from above was correct!

thx

**Comment by erd82** [comment]
Hi, if anyone else has the problem that the popup does not come up on the Android TV (mine is 55POS9002), just do a restart after enabling the USB Debugging mode.

**Comment by samsunga34sam-creator** [comment]
"Artel Smart TV qurilmamda 'Device Authorization' xatosi chiqyapti. Zavod sozlamalariga qaytardim (Reset qildim), lekin foydasi bo'lmadi. Ekrandagi Hardware ID raqami: 7C:82:74:C2:00:10. Iltimos, ushbu qurilmani server orqali faollashtirib (avtorizatsiya qilib) bering."
